// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

#ifndef PROTOBUF_paxos_2eproto__INCLUDED
#define PROTOBUF_paxos_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace libpaxos {
class BeginRound;
class BeginRoundDefaultTypeInternal;
extern BeginRoundDefaultTypeInternal _BeginRound_default_instance_;
class LastVote;
class LastVoteDefaultTypeInternal;
extern LastVoteDefaultTypeInternal _LastVote_default_instance_;
class NextRound;
class NextRoundDefaultTypeInternal;
extern NextRoundDefaultTypeInternal _NextRound_default_instance_;
class Ok;
class OkDefaultTypeInternal;
extern OkDefaultTypeInternal _Ok_default_instance_;
class Value;
class ValueDefaultTypeInternal;
extern ValueDefaultTypeInternal _Value_default_instance_;
class Voted;
class VotedDefaultTypeInternal;
extern VotedDefaultTypeInternal _Voted_default_instance_;
}  // namespace libpaxos

namespace libpaxos {

namespace protobuf_paxos_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_paxos_2eproto

// ===================================================================

class NextRound : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:libpaxos.NextRound) */ {
 public:
  NextRound();
  virtual ~NextRound();

  NextRound(const NextRound& from);

  inline NextRound& operator=(const NextRound& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NextRound& default_instance();

  static inline const NextRound* internal_default_instance() {
    return reinterpret_cast<const NextRound*>(
               &_NextRound_default_instance_);
  }

  void Swap(NextRound* other);

  // implements Message ----------------------------------------------

  inline NextRound* New() const PROTOBUF_FINAL { return New(NULL); }

  NextRound* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NextRound& from);
  void MergeFrom(const NextRound& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NextRound* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 roundNumber = 1;
  void clear_roundnumber();
  static const int kRoundNumberFieldNumber = 1;
  ::google::protobuf::uint64 roundnumber() const;
  void set_roundnumber(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:libpaxos.NextRound)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 roundnumber_;
  mutable int _cached_size_;
  friend struct  protobuf_paxos_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LastVote : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:libpaxos.LastVote) */ {
 public:
  LastVote();
  virtual ~LastVote();

  LastVote(const LastVote& from);

  inline LastVote& operator=(const LastVote& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LastVote& default_instance();

  static inline const LastVote* internal_default_instance() {
    return reinterpret_cast<const LastVote*>(
               &_LastVote_default_instance_);
  }

  void Swap(LastVote* other);

  // implements Message ----------------------------------------------

  inline LastVote* New() const PROTOBUF_FINAL { return New(NULL); }

  LastVote* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LastVote& from);
  void MergeFrom(const LastVote& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LastVote* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 roundNumber = 1;
  void clear_roundnumber();
  static const int kRoundNumberFieldNumber = 1;
  ::google::protobuf::uint64 roundnumber() const;
  void set_roundnumber(::google::protobuf::uint64 value);

  // uint64 lastValue = 2;
  void clear_lastvalue();
  static const int kLastValueFieldNumber = 2;
  ::google::protobuf::uint64 lastvalue() const;
  void set_lastvalue(::google::protobuf::uint64 value);

  // uint64 lastRound = 3;
  void clear_lastround();
  static const int kLastRoundFieldNumber = 3;
  ::google::protobuf::uint64 lastround() const;
  void set_lastround(::google::protobuf::uint64 value);

  // bool accepted = 4;
  void clear_accepted();
  static const int kAcceptedFieldNumber = 4;
  bool accepted() const;
  void set_accepted(bool value);

  // @@protoc_insertion_point(class_scope:libpaxos.LastVote)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 roundnumber_;
  ::google::protobuf::uint64 lastvalue_;
  ::google::protobuf::uint64 lastround_;
  bool accepted_;
  mutable int _cached_size_;
  friend struct  protobuf_paxos_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BeginRound : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:libpaxos.BeginRound) */ {
 public:
  BeginRound();
  virtual ~BeginRound();

  BeginRound(const BeginRound& from);

  inline BeginRound& operator=(const BeginRound& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BeginRound& default_instance();

  static inline const BeginRound* internal_default_instance() {
    return reinterpret_cast<const BeginRound*>(
               &_BeginRound_default_instance_);
  }

  void Swap(BeginRound* other);

  // implements Message ----------------------------------------------

  inline BeginRound* New() const PROTOBUF_FINAL { return New(NULL); }

  BeginRound* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BeginRound& from);
  void MergeFrom(const BeginRound& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BeginRound* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 roundNumber = 1;
  void clear_roundnumber();
  static const int kRoundNumberFieldNumber = 1;
  ::google::protobuf::uint64 roundnumber() const;
  void set_roundnumber(::google::protobuf::uint64 value);

  // uint64 value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::google::protobuf::uint64 value() const;
  void set_value(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:libpaxos.BeginRound)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 roundnumber_;
  ::google::protobuf::uint64 value_;
  mutable int _cached_size_;
  friend struct  protobuf_paxos_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Voted : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:libpaxos.Voted) */ {
 public:
  Voted();
  virtual ~Voted();

  Voted(const Voted& from);

  inline Voted& operator=(const Voted& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Voted& default_instance();

  static inline const Voted* internal_default_instance() {
    return reinterpret_cast<const Voted*>(
               &_Voted_default_instance_);
  }

  void Swap(Voted* other);

  // implements Message ----------------------------------------------

  inline Voted* New() const PROTOBUF_FINAL { return New(NULL); }

  Voted* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Voted& from);
  void MergeFrom(const Voted& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Voted* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 roundNumber = 1;
  void clear_roundnumber();
  static const int kRoundNumberFieldNumber = 1;
  ::google::protobuf::uint64 roundnumber() const;
  void set_roundnumber(::google::protobuf::uint64 value);

  // uint64 lastRound = 2;
  void clear_lastround();
  static const int kLastRoundFieldNumber = 2;
  ::google::protobuf::uint64 lastround() const;
  void set_lastround(::google::protobuf::uint64 value);

  // bool accepted = 3;
  void clear_accepted();
  static const int kAcceptedFieldNumber = 3;
  bool accepted() const;
  void set_accepted(bool value);

  // @@protoc_insertion_point(class_scope:libpaxos.Voted)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 roundnumber_;
  ::google::protobuf::uint64 lastround_;
  bool accepted_;
  mutable int _cached_size_;
  friend struct  protobuf_paxos_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Ok : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:libpaxos.Ok) */ {
 public:
  Ok();
  virtual ~Ok();

  Ok(const Ok& from);

  inline Ok& operator=(const Ok& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Ok& default_instance();

  static inline const Ok* internal_default_instance() {
    return reinterpret_cast<const Ok*>(
               &_Ok_default_instance_);
  }

  void Swap(Ok* other);

  // implements Message ----------------------------------------------

  inline Ok* New() const PROTOBUF_FINAL { return New(NULL); }

  Ok* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Ok& from);
  void MergeFrom(const Ok& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Ok* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 roundNumber = 1;
  void clear_roundnumber();
  static const int kRoundNumberFieldNumber = 1;
  ::google::protobuf::uint64 roundnumber() const;
  void set_roundnumber(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:libpaxos.Ok)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 roundnumber_;
  mutable int _cached_size_;
  friend struct  protobuf_paxos_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Value : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:libpaxos.Value) */ {
 public:
  Value();
  virtual ~Value();

  Value(const Value& from);

  inline Value& operator=(const Value& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Value& default_instance();

  static inline const Value* internal_default_instance() {
    return reinterpret_cast<const Value*>(
               &_Value_default_instance_);
  }

  void Swap(Value* other);

  // implements Message ----------------------------------------------

  inline Value* New() const PROTOBUF_FINAL { return New(NULL); }

  Value* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Value& from);
  void MergeFrom(const Value& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Value* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 roundNumber = 1;
  void clear_roundnumber();
  static const int kRoundNumberFieldNumber = 1;
  ::google::protobuf::uint64 roundnumber() const;
  void set_roundnumber(::google::protobuf::uint64 value);

  // uint64 value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::google::protobuf::uint64 value() const;
  void set_value(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:libpaxos.Value)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 roundnumber_;
  ::google::protobuf::uint64 value_;
  mutable int _cached_size_;
  friend struct  protobuf_paxos_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// NextRound

// uint64 roundNumber = 1;
inline void NextRound::clear_roundnumber() {
  roundnumber_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 NextRound::roundnumber() const {
  // @@protoc_insertion_point(field_get:libpaxos.NextRound.roundNumber)
  return roundnumber_;
}
inline void NextRound::set_roundnumber(::google::protobuf::uint64 value) {
  
  roundnumber_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.NextRound.roundNumber)
}

// -------------------------------------------------------------------

// LastVote

// uint64 roundNumber = 1;
inline void LastVote::clear_roundnumber() {
  roundnumber_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LastVote::roundnumber() const {
  // @@protoc_insertion_point(field_get:libpaxos.LastVote.roundNumber)
  return roundnumber_;
}
inline void LastVote::set_roundnumber(::google::protobuf::uint64 value) {
  
  roundnumber_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.LastVote.roundNumber)
}

// uint64 lastValue = 2;
inline void LastVote::clear_lastvalue() {
  lastvalue_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LastVote::lastvalue() const {
  // @@protoc_insertion_point(field_get:libpaxos.LastVote.lastValue)
  return lastvalue_;
}
inline void LastVote::set_lastvalue(::google::protobuf::uint64 value) {
  
  lastvalue_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.LastVote.lastValue)
}

// uint64 lastRound = 3;
inline void LastVote::clear_lastround() {
  lastround_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LastVote::lastround() const {
  // @@protoc_insertion_point(field_get:libpaxos.LastVote.lastRound)
  return lastround_;
}
inline void LastVote::set_lastround(::google::protobuf::uint64 value) {
  
  lastround_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.LastVote.lastRound)
}

// bool accepted = 4;
inline void LastVote::clear_accepted() {
  accepted_ = false;
}
inline bool LastVote::accepted() const {
  // @@protoc_insertion_point(field_get:libpaxos.LastVote.accepted)
  return accepted_;
}
inline void LastVote::set_accepted(bool value) {
  
  accepted_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.LastVote.accepted)
}

// -------------------------------------------------------------------

// BeginRound

// uint64 roundNumber = 1;
inline void BeginRound::clear_roundnumber() {
  roundnumber_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BeginRound::roundnumber() const {
  // @@protoc_insertion_point(field_get:libpaxos.BeginRound.roundNumber)
  return roundnumber_;
}
inline void BeginRound::set_roundnumber(::google::protobuf::uint64 value) {
  
  roundnumber_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.BeginRound.roundNumber)
}

// uint64 value = 2;
inline void BeginRound::clear_value() {
  value_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BeginRound::value() const {
  // @@protoc_insertion_point(field_get:libpaxos.BeginRound.value)
  return value_;
}
inline void BeginRound::set_value(::google::protobuf::uint64 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.BeginRound.value)
}

// -------------------------------------------------------------------

// Voted

// uint64 roundNumber = 1;
inline void Voted::clear_roundnumber() {
  roundnumber_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Voted::roundnumber() const {
  // @@protoc_insertion_point(field_get:libpaxos.Voted.roundNumber)
  return roundnumber_;
}
inline void Voted::set_roundnumber(::google::protobuf::uint64 value) {
  
  roundnumber_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.Voted.roundNumber)
}

// uint64 lastRound = 2;
inline void Voted::clear_lastround() {
  lastround_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Voted::lastround() const {
  // @@protoc_insertion_point(field_get:libpaxos.Voted.lastRound)
  return lastround_;
}
inline void Voted::set_lastround(::google::protobuf::uint64 value) {
  
  lastround_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.Voted.lastRound)
}

// bool accepted = 3;
inline void Voted::clear_accepted() {
  accepted_ = false;
}
inline bool Voted::accepted() const {
  // @@protoc_insertion_point(field_get:libpaxos.Voted.accepted)
  return accepted_;
}
inline void Voted::set_accepted(bool value) {
  
  accepted_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.Voted.accepted)
}

// -------------------------------------------------------------------

// Ok

// uint64 roundNumber = 1;
inline void Ok::clear_roundnumber() {
  roundnumber_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ok::roundnumber() const {
  // @@protoc_insertion_point(field_get:libpaxos.Ok.roundNumber)
  return roundnumber_;
}
inline void Ok::set_roundnumber(::google::protobuf::uint64 value) {
  
  roundnumber_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.Ok.roundNumber)
}

// -------------------------------------------------------------------

// Value

// uint64 roundNumber = 1;
inline void Value::clear_roundnumber() {
  roundnumber_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Value::roundnumber() const {
  // @@protoc_insertion_point(field_get:libpaxos.Value.roundNumber)
  return roundnumber_;
}
inline void Value::set_roundnumber(::google::protobuf::uint64 value) {
  
  roundnumber_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.Value.roundNumber)
}

// uint64 value = 2;
inline void Value::clear_value() {
  value_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Value::value() const {
  // @@protoc_insertion_point(field_get:libpaxos.Value.value)
  return value_;
}
inline void Value::set_value(::google::protobuf::uint64 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:libpaxos.Value.value)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace libpaxos

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_paxos_2eproto__INCLUDED
